package com.example.quantum.enums;

public enum Sector {
    ADMINISTRATIVO,
    ALMOXARIFADO,
    COMPRAS,
    DEPARTAMENTO_PESSOAL,
    RECURSOS_HUMANOS,
    FINANCEIRO,
    INPECAO,
    DIRECAO,
    QUALIDADE,
    PLANEJAMENTO,
    SEGURANCA_DO_TRABALHO,
    TECNOLOGIA_DA_INFORMACAO,
    DETALHAMENTO,
    COMERCIAL,
    PINTURA,
    MANUTENCAO
}